spring:
  application:
    name: "elastic-search"
  kafka:
    bootstrap-servers: localhost:29092
    consumer:
      group-id: "elastic-search"
      auto-offset-reset: earliest
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.springframework.kafka.support.serializer.JsonDeserializer
      properties:
        spring:
          json:
            trusted:
              packages: '*'


topic:
  send-order: video-streaming
server:
  port: 0
eureka:
  client:
    serviceUrl:
      defaultZone: ${EUREKA_URI:http://localhost:8081/eureka}
  instance:
    preferIpAddress: true